on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Railway
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy
        run: railway up 
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}